# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Design' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Design

pod 'Firebase/Core'
pod 'FirebaseUI'

  target 'DesignTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DesignUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
